site_name: 脚著谢公屐

copyright: Copyright &copy; 2023 - 2024 Wang Zhao

theme:
  name: material
  language: zh

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode


extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/JZXGJ

    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/jzxgj

  generator: false
