site_name: 脚著谢公屐

copyright: Copyright &copy; 2023 - 2024 Wang Zhao

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
  favicon: assets/images/favicon.png
  icon:
    logo: fontawesome/solid/feather-pointed

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode


extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/JZXGJ

    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/jzxgj

  generator: false


nav:
  - Home: index.md
  - 科学:
    - 科学：猜想和反驳: 科学：猜想和反驳.md
    - Big history: big_history.md
    - Sagnac Effect: Sagnac Effect.md

  - 计算机:
    - 编程珠玑: 编程珠玑.md
    - Unix 发展简史: Unix 发展.md
    - ChatGPT: What Is ChatGPT Doing/What Is ChatGPT Doing.md
  - 经济:
    - 比较优势: Comparative_advantage/比较优势.md
    - 四种花钱方法: Economy/Friedman.md
  - 电影:
    - IMDb Top 250 Movies: IMDB_TOP250.md
  - 航天:
    - 瓢虫一号轨道: PC1\瓢虫一号.md


markdown_extensions:
  # for math
  - pymdownx.arithmatex:
      generic: true

# for math
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js